---
title: "Drobci"
author: "A. Blejec"
date: "09 januar 2019"
output: html_document
---

```{r setup, include=FALSE}
## parametri, ki veljajo za vse chunke
knitr::opts_chunk$set(echo = TRUE,fig.width=10,fig.height=10)
par(mar=c(4,4,2,1))
```

## Velikosti panelov v slikah

```{r}
par(mfrow=c(2,2))
m <- prod(par("mfrow"))
for(i in 1:m){
plot(1:10,main=i)
box("fig",col=i)
}
```

## Funkcija `approx`

Slučajna števila s pomočjo inverzne porazdelitvene funkcije

Generirajmo porazdelitev z neko empirično gostoto

```{r}
n <- 100
u <- runif(n)^2
u <- sort(u)
hist(u)
rug(u)
```

```{r}
plot(u, (rank(u)-0.5)/n)
```



Empirična porazdelitvena funkcija

```{r}
P <- (rank(u)-0.5)/n
approx(u,P,0.5)
pD <- approxfun(u,P,yleft=min(u),yright=max(u))
plot(u,pD(u),type="b")
```

```{r}
plot(u^2)
```

```{r}
m=median(u)
pD(m)
```

Kvantili

```{r}
qD=approxfun(P,u,yleft=min(P),yright=max(P))
qD(0.5)==median(u)
abs(qD(0.5)-median(u))< 10^(-8)
```

Slučajna števila

```{r}
rD <- function(n=100)    qD(runif(n))
rD(20)
```

```{r}
x <- rD(200)
plot(x,rank(x))
```


## Funkcija `optim`


```{r}
sumsq <- function(par,x,y
                  ){
  a <- par[1]
  b <- par[2]
  yhat <- a+b*x
  d2 <- sum((y-yhat)^2)
  return(d2)
}
```


Podatki
```{r}
n <- 10
a <- 1
b <- 3
serr <- 1
x <- rnorm(n)
eps <- rnorm(n,sd = serr)
y <- a + b * x + eps
plot(x,y)
X <- x
Y <- y
abline(lm(y~x),col="red")
```

Optimizacija

```{r}
optim(par=c(0,1),sumsq,x=x,y=y)
lm( y ~ x)
```

Absolutni odkloni


```{r}
sumsqa <- function(par,x,y
                  ){
  a <- par[1]
  b <- par[2]
  yhat <- a+b*x
  d2 <- sum(abs(y-yhat))
  return(d2)
}
```

```{r}
pabs <- optim(par=c(0,1),sumsqa,x=x,y=y)
pabs
lm( y ~ x)
```

```{r}
plot(x,y)
abline(lm(y~x),col="red")
abline(pabs$par,col="blue")
```

